#!/bin/sh

cd "$HOME"

echo "Init submodules"
yadm submodule set-url .config/nvim "https://github.com/kewuaa/nvim.git"
yadm submodule update --init --recursive
yadm submodule set-url .config/nvim "git@github.com:kewuaa/nvim.git"

echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:kewuaa/dotfiles.git"
