#!/bin/sh

# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.
# River will send the process group of the init executable SIGTERM on exit.
# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal

kwm &
